sudo: false
language: python
python:
- '3.5'
env:
  global:
  - PIP_RETRIES=10
  - PIP_TIMEOUT=30
  - BROWSER=firefox
  matrix:
  - TOXENV=checkqa
  - TOXENV=base-py35-django20-sqlite
addons:
  firefox: "45.4.0esr"
matrix:
  allow_failures:
  - env: TOXENV=base-py35-djangomaster-sqlite
install:
- travis_retry pip install -U pip
- travis_retry pip install tox
- travis_retry pip freeze
before_script:
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
- sleep 3 # give xvfb some time to start
- wget https://github.com/mozilla/geckodriver/releases/download/v0.11.1/geckodriver-v0.11.1-linux64.tar.gz
- mkdir geckodriver
- tar -xzf geckodriver-v0.11.1-linux64.tar.gz -C geckodriver
- export PATH=$PATH:$PWD/geckodriver
script:
- whereis chromedriver
- tox -r
- test -d .tox/$TOXENV/log && cat .tox/$TOXENV/log/*.log || true
after_success:
- travis_retry pip install codecov
- cd test_project && codecov
notifications:
  irc:
    channels:
    - irc.freenode.org#yourlabs
    template:
    - "%{repository} (%{commit} %{author}) : %{message} %{build_url} %{compare_url}"
cache:
  directories:
  - .tox/$TOXENV
  - $HOME/.cache/pip
  - $HOME/travis_phantomjs
deploy:
  provider: openshift
  user: jpic@yourlabs.org
  password:
    secure: FuIzy9CJ1+SSsLFVXj942Y4DYzv2NLAktHML+VB3IBR+JdJ4cTW7lftwUmmghXE4HmBoHbKsDlpwN/dErPy0yDl2bv3ejJWRWyekIOyu0Omwia0PDTEt6n/mryrQ92dAyjpD6SeypotHqhOCnj1HxJdgwL4EmzG+5o9n8eNte0M=
  app: dal
  domain: yourlabs
  deployment_branch: master
  skip_cleanup: true
  on:
    repo: yourlabs/django-autocomplete-light
    branch: master
